### ISSUE TITLE
PublicKeyFingerprintMismatch

### ISSUE THREAD

**Issue by yongzhang** [mozillazg/alibabacloud-oidc-auth#22]
Hi, I experience this issue today, please help, thanks.

```
mozillazg/alibabacloud-oidc-auth failed with: retry function failed after 4 attempts: authenticationFail.OIDCToken.PublicKeyFingerprintMismatch: code: 401, The https fingerprint of this discovery is invalid.
```

**Comment by yongzhang** [comment]
ok, found the cause. See https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws. There are 2 thumbprints now:

```
6938fd4d98bab03faadb97b34396831e3780aea1
1c58a3a8518e8759bf075b76b750d4f2df264fcd
```

**Comment by mozillazg** [comment]
> ok, found the cause. See https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws. There are 2 thumbprints now:
> 
> ```
> 6938fd4d98bab03faadb97b34396831e3780aea1
> 1c58a3a8518e8759bf075b76b750d4f2df264fcd
> ```

@yongzhang Thanks for sharing.

**Comment by mozillazg** [comment]
The latest fingerprints:
```
d89e3bd43d5d909b47a18977aa9d5ce36cee184c
33e4e80807204c2b6182a3a14b591acd25b5f0db
74f3a68f16524f15424927704c9506f55a9316bd
```
