### ISSUE TITLE
Transitioning from Node 16 to Node 20

### ISSUE THREAD

**Issue by vbem** [mozillazg/alibabacloud-oidc-auth#44]
Dear,

Hope this issue finds you well.

In recent days using `mozillazg/alibabacloud-oidc-auth@v1`, I found there is a warning in workflow runs:

```plain
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mozillazg/alibabacloud-oidc-auth@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

So could you please kindly update this fantastic action? 谢谢老铁~ ^_^

**Comment by mozillazg** [comment]
Thanks for your reporting! The latest version already fixed this warning.
