### ISSUE TITLE
Support ALICLOUD_SECURITY_TOKEN in environment variables

### ISSUE THREAD

**Issue by yongzhang** [mozillazg/alibabacloud-oidc-auth#8]
Hi, there

Thanks for sharing this project, this is great and very useful!

It would be nice to support `ALICLOUD_SECURITY_TOKEN` in environment variables, this will be used in aliyun terraform provider, thanks!!!

Ref:
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs#security_token

![image](https://user-images.githubusercontent.com/15604715/215433960-dc694898-4f45-4845-964d-daee0a1f2bf8.png)

**Comment by mozillazg** [comment]
The latest version already supports it.
